### ISSUE TITLE
iOS 17 PlatformException(401, The user has not allowed this application to modify their calendar(s), null, null)

### ISSUE THREAD

**Issue by FySanta** [builttoroam/flutter_plugins#561]
ios 17.0  
var calendarsResult = await _deviceCalendarPlugin.retrieveCalendars() has error PlatformException(401, The user has not allowed this application to modify their calendar(s), null, null)

   await _deviceCalendarPlugin.requestPermissions();
   await _deviceCalendarPlugin.hasPermissions();
   var calendarsResult = await _deviceCalendarPlugin.retrieveCalendars();

![31728382804_ pic](https://github.com/user-attachments/assets/6d486d19-acf0-4c38-827a-5eebc8253f32)
errorcode：599
errorMessage：Device calendar plugin ran into an issue. Platform specific exception [401], with message :"The user has not allowed this application to modify their calendar(s)", has been thrown.

When getting the fullaccess privileges for a calendar, running await _deviceCalendarPlugin.requestPermissions() gives true after the user grants the privileges, but await _deviceCalendarPlugin.hasPermissions() says is false, and only becomes true after restarting the app.

**Comment by IVLIVS-III** [comment]
make sure that this line of code `await _deviceCalendarPlugin.hasPermissions();` returns `true`. Otherwise permissions have not been granted.

**Comment by FySanta** [comment]
> 确保此行代码`await _deviceCalendarPlugin.hasPermissions();`返回`true`。否则权限未授予。

It shows authorized inside the app settings, but `await _deviceCalendarPlugin.hasPermissions()` return false

**Comment by FySanta** [comment]
![91728439398_ pic](https://github.com/user-attachments/assets/7dcb1909-4bac-40c5-adfc-63b731be52fa)

**Comment by IVLIVS-III** [comment]
That is strange, can you provide a minimum example to reproduce this issue?

**Comment by FySanta** [comment]
Here's my running order
`    await _deviceCalendarPlugin.requestPermissions();
    await _deviceCalendarPlugin.hasPermissions();
    var calendarsResult = await _deviceCalendarPlugin.retrieveCalendars();`

**Comment by FySanta** [comment]
> That is strange, can you provide a minimum example to reproduce this issue?

Here's my running order
```
await _deviceCalendarPlugin.requestPermissions(); 
await _deviceCalendarPlugin.hasPermissions(); 
var calendarsResult = await _deviceCalendarPlugin.retrieveCalendars();
```
You can check separately the permission status returned by these two lines of code.
```
await _deviceCalendarPlugin.requestPermissions(); 
await _deviceCalendarPlugin.hasPermissions(); 
```

**Comment by achapkey** [comment]
Ran into the similar issue. Could not get permission request at all. It even didn't appear in system settings. Worked it around via requesting the permission from permission_handler, but it requires relaunching the app to retrieve the calendar list. Moreover, it reproduces only on 17.0, on 17.2 and higher works like charm (couldn't get my hands on iOS 17.1).

**Comment by HatsuneMikuV** [comment]
```
private func requestPermissions(completion: @escaping (Bool) -> Void) {
        if hasEventPermissions() {
            completion(true)
            return
        }
        if #available(iOS 17, *) {
            eventStore.requestFullAccessToEvents {
                (accessGranted: Bool, _: Error?) in
                completion(accessGranted)
            }
        } else {
            eventStore.requestAccess(to: .event, completion: {
                (accessGranted: Bool, _: Error?) in
                completion(accessGranted)
            })
        }
    }
    private func requestPermissions(_ result: @escaping FlutterResult) {
        if hasEventPermissions()  {
            result(true)
        }
        eventStore.requestAccess(to: .event, completion: {
            (accessGranted: Bool, _: Error?) in
            result(accessGranted)
        })
    }
    
```
    

> https://github.com/builttoroam/device_calendar/blob/8cd4161bc5ece4ebbfb09f009cade8a08946aead/ios/Classes/SwiftDeviceCalendarPlugin.swift#L914
> 
> https://github.com/builttoroam/device_calendar/blob/8cd4161bc5ece4ebbfb09f009cade8a08946aead/ios/Classes/SwiftDeviceCalendarPlugin.swift#L941

It should be caused by two methods with the same name

**Comment by deezaster** [comment]
same problem with IOS 18.1 and 18.2.!
is there a workaround I can implement? or did someone fork this project? when will this bug be fixed?

**Comment by gavira** [comment]
I believe it's this issue: https://forums.developer.apple.com/forums/thread/739315
My fork should fix it:
```
device_calendar:
    git:
      url: https://github.com/gavira/device_calendar.git
      ref: fixIos18
```

**Comment by IVLIVS-III** [comment]
@gavira awesome, thank you for your work. Please open a pull request against the `develop` branch. This way your fix can be directly included in the published plugin once the next version is submitted.

**Comment by lan2000** [comment]
> 我相信这是这个问题：https://forums.developer.apple.com/forums/thread/739315 我的叉子应该修复它：
> 
> ```
> device_calendar:
>     git:
>       url: https://github.com/gavira/device_calendar.git
>       ref: fixIos18
> ```

Hello, after testing, the following error still appears in iOS 17.1 until the app is restarted.

`﻿PlatformException(401, The user has not allowed this application to modify their calendar(s), null, null)`

**Comment by illuminated** [comment]
I've spent a couple of days trying to fix this in a project and ended up creating a minimal flutter test to see if I can somehow retrieve the on-device calendars right upon the permission granted event. I ended up doing a native permission request and calendar retrieval. I'll post here my minimal example so whoever has an issue can use the same technique until it becomes available through one of next releases.

ios/Runner/AppDelegate.swift
```
import UIKit
import Flutter
import EventKit

@main
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    GeneratedPluginRegistrant.register(with: self)
    
    let controller = window?.rootViewController as! FlutterViewController
    let calendarChannel = FlutterMethodChannel(name: "calendar_permission_check",
                                              binaryMessenger: controller.binaryMessenger)
    
    calendarChannel.setMethodCallHandler { (call: FlutterMethodCall, result: @escaping FlutterResult) in
      switch call.method {
      case "checkCalendarPermission":
        self.checkCalendarPermission(result: result)
      case "requestCalendarPermission":
        self.requestCalendarPermission(result: result)
      case "requestAndWaitForPermission":
        self.requestAndWaitForPermission(result: result)
      case "retrieveCalendarsNative":
        self.retrieveCalendarsNative(result: result)
      default:
        result(FlutterMethodNotImplemented)
      }
    }
    
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
  
  private func checkCalendarPermission(result: @escaping FlutterResult) {
    let eventStore = EKEventStore()
    let status = EKEventStore.authorizationStatus(for: .event)
    
    print("Native iOS: EventKit authorization status: \(status.rawValue)")
    
    switch status {
    case .authorized:
      print("Native iOS: Calendar permission is granted (authorized)")
      result(true)
    case .denied, .restricted:
      print("Native iOS: Calendar permission is denied/restricted")
      result(false)
    case .notDetermined:
      print("Native iOS: Calendar permission is not determined")
      result(false)
    default:
      // Handle iOS 17+ cases if available
      if #available(iOS 17.0, *) {
        switch status {
        case .fullAccess:
          print("Native iOS: Calendar permission is granted (fullAccess)")
          result(true)
        case .writeOnly:
          print("Native iOS: Calendar permission is write-only")
          result(false)
        default:
          print("Native iOS: Unknown calendar permission status")
          result(false)
        }
      } else {
        print("Native iOS: Unknown calendar permission status for iOS < 17")
        result(false)
      }
    }
  }
  
  private func requestCalendarPermission(result: @escaping FlutterResult) {
    let eventStore = EKEventStore()
    
    print("Native iOS: Requesting calendar permission...")
    
    if #available(iOS 17.0, *) {
      eventStore.requestFullAccessToEvents { (granted, error) in
        DispatchQueue.main.async {
          print("Native iOS: Full access request completed - granted: \(granted), error: \(String(describing: error))")
          result(granted)
        }
      }
    } else {
      eventStore.requestAccess(to: .event) { (granted, error) in
        DispatchQueue.main.async {
          print("Native iOS: Access request completed - granted: \(granted), error: \(String(describing: error))")
          result(granted)
        }
      }
    }
  }
  
  private func requestAndWaitForPermission(result: @escaping FlutterResult) {
    let eventStore = EKEventStore()
    let initialStatus = EKEventStore.authorizationStatus(for: .event)
    
    print("Native iOS: Initial status: \(initialStatus.rawValue)")
    
    // Check if already authorized (compatible with all iOS versions)
    var isAlreadyAuthorized = false
    switch initialStatus {
    case .authorized:
      isAlreadyAuthorized = true
    default:
      if #available(iOS 17.0, *) {
        if initialStatus == .fullAccess {
          isAlreadyAuthorized = true
        }
      }
    }
    
    if isAlreadyAuthorized {
      print("Native iOS: Already authorized")
      result(true)
      return
    }
    
    // Request permission and wait for completion
    print("Native iOS: Requesting permission and waiting...")
    
    if #available(iOS 17.0, *) {
      eventStore.requestFullAccessToEvents { (granted, error) in
        print("Native iOS: Permission request completed - granted: \(granted)")
        
        if granted {
          // Wait a bit for the system to fully process the permission
          DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) {
            let finalStatus = EKEventStore.authorizationStatus(for: .event)
            print("Native iOS: Final status after wait: \(finalStatus.rawValue)")
            let isGranted = (finalStatus == .authorized || finalStatus == .fullAccess)
            result(isGranted)
          }
        } else {
          DispatchQueue.main.async {
            result(false)
          }
        }
      }
    } else {
      eventStore.requestAccess(to: .event) { (granted, error) in
        print("Native iOS: Permission request completed - granted: \(granted)")
        
        if granted {
          // Wait a bit for the system to fully process the permission
          DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) {
            let finalStatus = EKEventStore.authorizationStatus(for: .event)
            print("Native iOS: Final status after wait: \(finalStatus.rawValue)")
            let isGranted = (finalStatus == .authorized)
            result(isGranted)
          }
        } else {
          DispatchQueue.main.async {
            result(false)
          }
        }
      }
    }
  }
  
  private func retrieveCalendarsNative(result: @escaping FlutterResult) {
    let eventStore = EKEventStore()
    let status = EKEventStore.authorizationStatus(for: .event)
    
    print("Native iOS: Retrieving calendars with status: \(status.rawValue)")
    
    // Check if we have permission
    var hasPermission = false
    switch status {
    case .authorized:
      hasPermission = true
    default:
      if #available(iOS 17.0, *) {
        if status == .fullAccess {
          hasPermission = true
        }
      }
    }
    
    if !hasPermission {
      print("Native iOS: No permission to access calendars")
      result(FlutterError(code: "NO_PERMISSION", message: "Calendar permission not granted", details: nil))
      return
    }
    
    // Retrieve calendars
    let calendars = eventStore.calendars(for: .event)
    print("Native iOS: Found \(calendars.count) calendars")
    
    var calendarData: [[String: Any]] = []
    
    for calendar in calendars {
      // Get color safely - cgColor is available on EKCalendar
      var colorHex = "#000000" // Default black
      if let cgColor = calendar.cgColor {
        let uiColor = UIColor(cgColor: cgColor)
        colorHex = uiColor.hexString
      }
      
      let calendarInfo: [String: Any] = [
        "id": calendar.calendarIdentifier,
        "name": calendar.title,
        "isReadOnly": !calendar.allowsContentModifications,
        "color": colorHex,
        "type": calendar.type.rawValue
      ]
      calendarData.append(calendarInfo)
      print("Native iOS: Calendar - ID: \(calendar.calendarIdentifier), Name: \(calendar.title), ReadOnly: \(!calendar.allowsContentModifications)")
    }
    
    result(calendarData)
  }
}

// Extension to convert UIColor to hex string
extension UIColor {
  var hexString: String {
    let components = self.cgColor.components
    let r: CGFloat = components?[0] ?? 0.0
    let g: CGFloat = components?[1] ?? 0.0
    let b: CGFloat = components?[2] ?? 0.0
    
    let hexString = String.init(format: "#%02lX%02lX%02lX", lroundf(Float(r * 255)), lroundf(Float(g * 255)), lroundf(Float(b * 255)))
    return hexString
  }
}
```

lib/main.dart
```
import 'package:device_calendar/device_calendar.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:permission_handler/permission_handler.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Calendar Permission Test',
      home: const CalendarTestScreen(),
    );
  }
}

class CalendarTestScreen extends StatelessWidget {
  const CalendarTestScreen({super.key});

  // Create a method channel to directly check iOS EventKit permissions
  static const platform = MethodChannel('calendar_permission_check');

  // Check iOS EventKit permission status directly
  Future<bool> _checkNativePermissionStatus() async {
    try {
      debugPrint("Minimal App: Checking native iOS EventKit permission...");
      final bool isGranted = await platform.invokeMethod(
        'checkCalendarPermission',
      );
      debugPrint("Minimal App: Native permission status: $isGranted");
      return isGranted;
    } catch (e) {
      debugPrint("Minimal App: Error checking native permission: $e");
      return false;
    }
  }

  // Request permission and wait for it to be properly processed
  Future<bool> _requestAndWaitForPermission() async {
    try {
      debugPrint(
        "Minimal App: Requesting and waiting for native permission...",
      );
      final bool isGranted = await platform.invokeMethod(
        'requestAndWaitForPermission',
      );
      debugPrint(
        "Minimal App: Native permission request and wait result: $isGranted",
      );
      return isGranted;
    } catch (e) {
      debugPrint("Minimal App: Error in request and wait: $e");
      return false;
    }
  }

  // Retrieve calendars using native iOS EventKit directly
  Future<List<Map<String, dynamic>>?> _retrieveCalendarsNative() async {
    try {
      debugPrint("Minimal App: Retrieving calendars using native EventKit...");
      final List<dynamic> calendars = await platform.invokeMethod('retrieveCalendarsNative');
      debugPrint("Minimal App: Native retrieval successful - found ${calendars.length} calendars");
      
      // Convert the dynamic list to properly typed maps
      List<Map<String, dynamic>> calendarList = calendars.map((calendar) {
        // Convert each calendar object to Map<String, dynamic>
        Map<String, dynamic> calendarMap = Map<String, dynamic>.from(calendar as Map);
        return calendarMap;
      }).toList();
      
      for (var calendar in calendarList) {
        debugPrint("Minimal App: Native Calendar - ID: ${calendar['id']}, Name: ${calendar['name']}, ReadOnly: ${calendar['isReadOnly']}");
      }
      
      return calendarList;
    } catch (e) {
      debugPrint("Minimal App: Error retrieving calendars natively: $e");
      return null;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Calendar Permission & Read Test')),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            ElevatedButton(
              onPressed: () async {
                debugPrint(
                  "Minimal App: Starting native permission request process...",
                );

                // First check current native status
                final initialNative = await _checkNativePermissionStatus();
                debugPrint(
                  "Minimal App: Initial native status: $initialNative",
                );

                if (initialNative) {
                  debugPrint(
                    "Minimal App: Already have native permission, retrieving calendars...",
                  );
                  await _retrieveCalendars();
                  return;
                }

                // Use native permission request with wait
                final nativeGranted = await _requestAndWaitForPermission();

                if (nativeGranted) {
                  debugPrint(
                    "Minimal App: Native permission granted and processed!",
                  );
                  await _retrieveCalendars();
                } else {
                  debugPrint("Minimal App: Native permission denied or failed");
                  // Fallback to permission_handler for opening settings
                  await openAppSettings();
                }
              },
              child: const Text('Request Calendar Permission (Native)'),
            ),
            const SizedBox(height: 20),
            ElevatedButton(
              onPressed: () async {
                debugPrint("Minimal App: Using permission_handler approach...");

                final PermissionStatus status = await Permission
                    .calendarFullAccess
                    .request();
                debugPrint("Minimal App: permission_handler result: $status");

                if (status.isGranted) {
                  // Even if permission_handler says granted, check native status
                  final nativeStatus = await _checkNativePermissionStatus();
                  debugPrint(
                    "Minimal App: Native status after permission_handler: $nativeStatus",
                  );

                  if (nativeStatus) {
                    await _retrieveCalendars();
                  } else {
                    debugPrint(
                      "Minimal App: permission_handler granted but native not ready",
                    );
                    if (context.mounted) {
                      _showPermissionInstructions(context);
                    }
                  }
                }
              },
              style: ElevatedButton.styleFrom(backgroundColor: Colors.orange),
              child: const Text('Request Permission (permission_handler)'),
            ),
            const SizedBox(height: 20),
            ElevatedButton(
              onPressed: () async {
                await _retrieveCalendars();
              },
              child: const Text('Retrieve Calendars'),
            ),
            const SizedBox(height: 20),
            ElevatedButton(
              onPressed: () async {
                await _checkNativePermissionStatus();
              },
              style: ElevatedButton.styleFrom(backgroundColor: Colors.green),
              child: const Text('Check Native Permission'),
            ),
            const SizedBox(height: 20),
            ElevatedButton(
              onPressed: () async {
                debugPrint("Minimal App: Attempting to sync permission states...");
                
                // Check both states
                final native = await _checkNativePermissionStatus();
                final handler = await Permission.calendarFullAccess.status;
                debugPrint("Minimal App: Before sync - Native: $native, Handler: $handler");
                
                if (native && !handler.isGranted) {
                  debugPrint("Minimal App: Native granted but handler denied - forcing handler request...");
                  await Permission.calendarFullAccess.request();
                  await Future.delayed(const Duration(milliseconds: 1000));
                  
                  final newHandler = await Permission.calendarFullAccess.status;
                  debugPrint("Minimal App: After handler request: $newHandler");
                } else if (!native && handler.isGranted) {
                  debugPrint("Minimal App: Handler granted but native denied - requesting native...");
                  await _requestAndWaitForPermission();
                  
                  final newNative = await _checkNativePermissionStatus();
                  debugPrint("Minimal App: After native request: $newNative");
                }
                
                // Final check
                final finalNative = await _checkNativePermissionStatus();
                final finalHandler = await Permission.calendarFullAccess.status;
                debugPrint("Minimal App: Final state - Native: $finalNative, Handler: $finalHandler");
                
                if (finalNative && finalHandler.isGranted) {
                  debugPrint("Minimal App: Both permissions aligned - trying calendar access...");
                  await _retrieveCalendars();
                }
              },
              style: ElevatedButton.styleFrom(backgroundColor: Colors.purple),
              child: const Text('Sync Permissions & Retrieve'),
            ),
            const SizedBox(height: 20),
            ElevatedButton(
              onPressed: () async {
                final calendars = await _retrieveCalendarsNative();
                if (calendars != null) {
                  debugPrint("Minimal App: Successfully retrieved ${calendars.length} calendars using native method!");
                } else {
                  debugPrint("Minimal App: Failed to retrieve calendars using native method");
                }
              },
              style: ElevatedButton.styleFrom(backgroundColor: Colors.red),
              child: const Text('Retrieve Calendars (Native)'),
            ),
            const SizedBox(height: 20),
            ElevatedButton(
              onPressed: () async {
                debugPrint("Minimal App: Full native permission and retrieval test...");
                
                // Step 1: Request native permission
                final hasPermission = await _requestAndWaitForPermission();
                if (!hasPermission) {
                  debugPrint("Minimal App: Failed to get native permission");
                  return;
                }
                
                // Step 2: Retrieve using native method
                final calendars = await _retrieveCalendarsNative();
                if (calendars != null) {
                  debugPrint("Minimal App: SUCCESS! Full native flow worked - retrieved ${calendars.length} calendars");
                } else {
                  debugPrint("Minimal App: Native permission granted but retrieval failed");
                }
              },
              style: ElevatedButton.styleFrom(backgroundColor: Colors.teal),
              child: const Text('Full Native Test'),
            ),
          ],
        ),
      ),
    );
  }

  void _showPermissionInstructions(BuildContext context) {
    // Ensure we're in a valid Material context before showing dialog
    if (!context.mounted) return;

    showDialog(
      context: context,
      builder: (BuildContext context) {
        return AlertDialog(
          title: const Text('Permission Granted'),
          content: const Text(
            'Calendar permission has been granted! Please try the native permission button '
            'or use the "Retrieve Calendars" button to test access.',
          ),
          actions: [
            TextButton(
              onPressed: () {
                Navigator.of(context).pop();
              },
              child: const Text('OK'),
            ),
          ],
        );
      },
    );
  }

  Future<void> _retrieveCalendars() async {
    debugPrint("Minimal App: Checking calendar permission status...");
    
    // Check native permission status first
    final nativeStatus = await _checkNativePermissionStatus();
    debugPrint("Minimal App: Native permission status: $nativeStatus");
    
    // Also check permission_handler status for comparison
    final PermissionStatus currentStatus = await Permission.calendarFullAccess.status;
    debugPrint("Minimal App: permission_handler status: $currentStatus");

    // Use native permission status as the source of truth
    if (nativeStatus) {
      debugPrint("Minimal App: Native permission is granted. Attempting to retrieve calendars...");
      DeviceCalendarPlugin deviceCalendarPlugin = DeviceCalendarPlugin();
      try {
        var calendarsResult = await deviceCalendarPlugin.retrieveCalendars();
        if (calendarsResult.hasErrors) {
          debugPrint("Minimal App: Error retrieving calendars: ${calendarsResult.errors.map((e) => e.errorMessage).join(", ")}");
          
          // If we get a 401 error despite native permission being granted,
          // there might be a mismatch between EventKit and device_calendar plugin
          if (calendarsResult.errors.any((e) => e.errorMessage.contains('401'))) {
            debugPrint("Minimal App: Got 401 error despite native permission. This suggests a plugin issue.");
            debugPrint("Minimal App: Trying to force permission refresh...");
            
            // Try requesting permission_handler permission to sync state
            await Permission.calendarFullAccess.request();
            await Future.delayed(const Duration(milliseconds: 1000));
            
            // Try again
            var retryResult = await deviceCalendarPlugin.retrieveCalendars();
            if (retryResult.hasErrors) {
              debugPrint("Minimal App: Retry also failed: ${retryResult.errors.map((e) => e.errorMessage).join(", ")}");
            } else if (retryResult.data == null || retryResult.data!.isEmpty) {
              debugPrint("Minimal App: Retry succeeded but no calendars found.");
            } else {
              debugPrint("Minimal App: Retry successful! Retrieved ${retryResult.data!.length} calendars:");
              for (var calendar in retryResult.data!) {
                debugPrint("Minimal App: Calendar: ID=${calendar.id}, Name=${calendar.name}, ReadOnly=${calendar.isReadOnly}");
              }
            }
          }
        } else if (calendarsResult.data == null || calendarsResult.data!.isEmpty) {
          debugPrint("Minimal App: No calendars found or data is null.");
        } else {
          debugPrint("Minimal App: Successfully retrieved ${calendarsResult.data!.length} calendars:");
          for (var calendar in calendarsResult.data!) {
            debugPrint("Minimal App: Calendar: ID=${calendar.id}, Name=${calendar.name}, ReadOnly=${calendar.isReadOnly}");
          }
        }
      } catch (e) {
        debugPrint("Minimal App: Exception while retrieving calendars: $e");
        if (e is Exception && e.toString().contains('PlatformException(401')) {
          debugPrint("Minimal App: Caught PlatformException(401) despite native permission being granted!");
          debugPrint("Minimal App: This suggests the device_calendar plugin is not recognizing the permission.");
          
          // Try to force sync the permission state
          debugPrint("Minimal App: Attempting to sync permission state...");
          await Permission.calendarFullAccess.request();
          await Future.delayed(const Duration(milliseconds: 1000));
          
          // Create a new plugin instance and try again
          DeviceCalendarPlugin newPlugin = DeviceCalendarPlugin();
          try {
            var retryResult = await newPlugin.retrieveCalendars();
            if (retryResult.hasErrors) {
              debugPrint("Minimal App: Sync retry failed: ${retryResult.errors.map((e) => e.errorMessage).join(", ")}");
            } else {
              debugPrint("Minimal App: Sync retry successful!");
              for (var calendar in retryResult.data!) {
                debugPrint("Minimal App: Calendar: ID=${calendar.id}, Name=${calendar.name}, ReadOnly=${calendar.isReadOnly}");
              }
            }
          } catch (retryE) {
            debugPrint("Minimal App: Sync retry exception: $retryE");
          }
        }
      }
    } else {
      debugPrint("Minimal App: Native permission not granted. Cannot retrieve calendars.");
      debugPrint("Minimal App: Note: permission_handler shows $currentStatus but native shows false");
    }
  }
}
```

Podfile, at the end:
```
...
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
          '$(inherited)',
          'PERMISSION_CALENDAR=1',
          'PERMISSION_EVENTS=1',
          'PERMISSION_EVENTS_FULL_ACCESS=1',
          'PERMISSION_CONTACTS=1'
        ]
      end
    end
  end
```

Info.plist:
```
...
	<key>NSCalendarsUsageDescription</key>
	<string>Test app needs calendar access to test permissions.</string>
	<key>NSCalendarsFullAccessUsageDescription</key>
	<string>Test app needs full calendar access to test permissions.</string>
	<key>NSLocalNetworkUsageDescription</key>
	<string>This app uses local network access for Flutter debugging and development features.</string>
...
```
There are some unneeded pieces above, but you'll figure it out. Important thing is - it works. If you run the example and click the "Full native test" it should ask you for full calendar permission and right after successfully retrieve on-device calendars (check the logs). Then you can get back to device_calendar and permission_handler.

**Comment by toddanglin** [comment]
I think I'm encountering this same issue in iOS 18.6. I presume no fix for this has been added to device_calendar as of v4.3.3?

I'll give @illuminated's solution a try next.

Update: I ultimately implemented a native code solution based on what @illuminated and that seems to have solved the problem. Much trickier to solve that it seems on the surface! Hopefully this plugin will eventually offer a more robust solution for iOS again.

**Comment by nolann-dev** [comment]
I found a solution for this issue. If you use permission_handler to request calendar access, it works, but keep in mind that device_calendar manages its own permission state internally. There are two approaches:

1. Use the built-in device_calendar methods to request and check permissions.
2. If you use permission_handler, after granting calendar access, call `hasPermissions()` from device_calendar to update its internal state.

https://github.com/builttoroam/device_calendar/blob/2e0c2050d48c9bd2eb3cfc47650fbd63b1490ea5/lib/src/device_calendar.dart#L45

Does anyone know if syncing the permission state this way resolves the issue consistently across both iOS 17 and 18, or are there edge cases where this workaround fails?

**Comment by galacticgibbon** [comment]
> Use the built-in device_calendar methods to request and check permissions.

This doesn't work

**Comment by mhamdanx** [comment]
> I believe it's this issue: https://forums.developer.apple.com/forums/thread/739315 My fork should fix it:
> 
> ```
> device_calendar:
>     git:
>       url: https://github.com/gavira/device_calendar.git
>       ref: fixIos18
> ```

does not work!

**Comment by mhamdanx** [comment]
You can refresh `EKEventStore` and that should do the trick.  (Opened #605)


```swift
private func requestPermissions(_ completion: @escaping (Bool) -> Void) {
    if hasEventPermissions() {
        // Permission already granted – refresh the store
        self.eventStore = EKEventStore()
        completion(true)
        return
    }

    if #available(iOS 17, *) {
        eventStore.requestFullAccessToEvents { (accessGranted, _) in
            if accessGranted {
                self.eventStore = EKEventStore() // refresh store after granting
            }
            completion(accessGranted)
        }
    } else {
        eventStore.requestAccess(to: .event) { (accessGranted, _) in
            if accessGranted {
                self.eventStore = EKEventStore() // refresh store after granting
            }
            completion(accessGranted)
        }
    }
}


```


As for those relying on Permission_handler, simple use `Platform.iOS` and call `device_plugin.requestPermissions` only for ios. 
You can still validate stuff against permission_handler for the rest of your logic

**Comment by galacticgibbon** [comment]
This issue caused me to create my own device calendar implementation which doesn't suffer from many of the bugs that this package does.

I use it in prod in my own app. It also has no dependency on timezones, doesn't suffer from this particular bug, has integration tests. Lacks some features that this one has, but the features supported are properly implemented. I have a lot of domain knowledge on timezones/dates.

https://pub.dev/packages/device_calendar_plus
